### ISSUE TITLE
Some resources won't be shown within NWBib

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#119] opened 2015-07-16 09:55 UTC
Examples:
http://lobid.org/nwbib/HT017529028
http://lobid.org/nwbib/HT017529054

They can be found and listed in a result list, eg.g. http://lobid.org/nwbib/search?set=HT012848847 but when you click on them it reads "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut oder kontaktieren Sie das Entwicklerteam, falls das Problem fortbesteht".

**Comment by dr0i** [comment] 2015-07-16 13:13
The API breaks because of an exception. The cause is an item without a proper ISIL ( see http://lobid.org/item/HT017529028::DI%20ESGA%2018.1), while this ISIL is taken for granted for some sorting in scala template at `app/views/tags/items_map.scala.html`. 
So this exception must be catched somehow (difficult for me to do in scala, but will have a look).
Another, maybe better solution would be to fix the data, the root of all evil.

**Comment by dr0i** [comment] 2015-07-16 13:17
This is the data which makes it hard to guess what item data is to be taken care of:

          <datafield tag="088" ind1=" " ind2=" ">
            <subfield code="b">MAG</subfield>
            <subfield code="c">DI ESGA 18.1</subfield>
            <subfield code="e">48</subfield>
          </datafield>
          <datafield tag="088" ind1=" " ind2=" ">
            <subfield code="a">1032</subfield>
            <subfield code="b">KOEL</subfield>
            <subfield code="c">PHBB 18/22/XVIII</subfield>
            <subfield code="e">Monographie</subfield>
          </datafield>
          <datafield tag="088" ind1=" " ind2=" ">
            <subfield code="a">Kn 28</subfield>
          </datafield>

Maybe it would be best to not mint item uris missing an ISIL.

**Comment by dr0i** [comment] 2015-07-17 09:57
> Maybe it would be best to not mint item uris missing an ISIL.

Did that. Please have a look @acka47 .

**Comment by acka47** [comment] 2015-07-17 09:57
+1

**Comment by dr0i** [comment] 2015-07-20 08:16
Deployed to production, closing.

**Closed by dr0i** 2015-07-20 08:16 UTC
Labels: bug, deploy, processing
