### ISSUE TITLE
Jump to  specific result list page

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#95] opened 2015-04-09 09:25 UTC
As a user I want to jump to a specific result list page.

**Comment by fsteeg** [comment] 2015-07-27 11:38
Duplicate of #26, but that is closed, so will work here.

**Comment by fsteeg** [comment] 2015-07-27 14:09
Deployed to staging: http://test.lobid.org/nwbib/search?q=ehrenfeld

**Comment by dr0i** [comment] 2015-07-27 14:17
+1

**Comment by acka47** [comment] 2015-08-03 09:37
+1

**Closed** 2015-08-04 11:41 UTC
