### ISSUE TITLE
Associate numbering with multi-volume work/series link

### ISSUE THREAD

**Issue by acka47** [hbz/nwbib#124] opened 2015-08-18 13:17 UTC
Based on https://github.com/lobid/lodmill/issues/497 (which is currently on staging only and latest on Thursday in production) we have to adjust the title view in NWBib.

Examples on test:

http://test.lobid.org/nwbib/BT000003404
http://test.lobid.org/nwbib/HT015440386 (This currently doesn't work, probably because of the changes.)

**Comment by fsteeg** [comment] 2015-08-19 07:38
The error you mentioned is actually caused by lobid-organisations, I opened https://github.com/hbz/lobid-organisations/issues/66.

**Comment by fsteeg** [comment] 2015-08-25 07:31
Deployed to staging, see:

http://test.lobid.org/nwbib/BT000003404
http://test.lobid.org/nwbib/HT015440386

**Comment by acka47** [comment] 2015-08-25 08:51
For a start, this is ok: +1 (I liked the the one-line solution you showed me better but there was the link problem.) Let's see what the customers say.

**Comment by acka47** [comment] 2015-08-25 08:54
As it probably has something to do with this issue: the link from articles to the resource they are contained in is now missing. See the results from http://test.lobid.org/nwbib/search?q=*&size=100&t=http%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2FArticle.

**Comment by fsteeg** [comment] 2015-08-25 09:31
Deployed to staging, see: http://test.lobid.org/nwbib/HT018629431

No label if there's a `bibliographicCitation`, else `Enthalten in`.

**Comment by acka47** [comment] 2015-08-25 09:46
+1

**Comment by fsteeg** [comment] 2015-08-26 09:01
Deployed to production, closing. See:

http://lobid.org/nwbib/BT000003404
http://lobid.org/nwbib/HT015440386
http://lobid.org/nwbib/HT018629431

**Closed** 2015-08-26 09:01 UTC
